version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: pytype
    versions:
    - 2021.1.28
    - 2021.2.19
    - 2021.2.23
    - 2021.2.9
    - 2021.3.10
    - 2021.3.22
    - 2021.3.3
    - 2021.4.1
    - 2021.4.9
  - dependency-name: marshmallow
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: flake8-annotations
    versions:
    - 2.5.0
    - 2.6.0
    - 2.6.1
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: flake8-bugbear
    versions:
    - 20.11.1
    - 21.3.1
    - 21.3.2
  - dependency-name: darglint
    versions:
    - 1.5.8
    - 1.6.0
    - 1.7.0
  - dependency-name: typeguard
    versions:
    - 2.10.0
    - 2.11.1
  - dependency-name: xdoctest
    versions:
    - 0.15.3
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
